version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: papuan
      POSTGRES_PASSWORD: papuan1234
      POSTGRES_DB: papuanhotal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: papuan@admin.com
      PGADMIN_DEFAULT_PASSWORD: papuan
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres-data:
